### ISSUE TITLE
FT - Maintain a github project

### ISSUE THREAD

**Issue by matheusbsilva** [Metrikgile/metrikgile-api#1]
Connect to Github API to get information about a project

- [ ] [US - Connect user by github account](https://github.com/Metrikgile/metrikgile-api/issues/2)
- [ ] [US - Lists repositories of the user connected](https://github.com/Metrikgile/metrikgile-api/issues/3)
- [ ] [US - Get projects information of the repository](https://github.com/Metrikgile/metrikgile-api/issues/4)
- [ ] [US - Get repository issues](https://github.com/Metrikgile/metrikgile-api/issues/5)
